-d D:\Verilog\tang\uart\impl\gwsynthesis\uart.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\Verilog\tang\uart\src\uart.cst
-cfg D:\Verilog\tang\uart\impl\pnr\device.cfg
-sdc D:\Verilog\tang\uart\src\uart.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
